# -*- coding: utf-8 -*-
"""Pizza otomasyonu AI Hub

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YJupQYZIn5DsYwFDUipyjoSmUy0uLpm-
"""

import csv
import datetime
import streamlit as st
import streamlit as st
import pandas as pd
import altair as alt

# Menu.txt dosyasını oluştur
with open("Menu.txt", "w") as f:
    f.write("* Lütfen Bir Pizza Tabanı Seçiniz:\n")
    f.write("1: Klasik\n")
    f.write("2: Margarita\n")
    f.write("3: TürkPizza\n")
    f.write("4: Sade Pizza\n")
    f.write("* ve seçeceğiniz sos:\n")
    f.write("11: Zeytin\n")
    f.write("12: Mantarlar\n")
    f.write("13: Keçi Peyniri\n")
    f.write("14: Et\n")
    f.write("15: Soğan\n")
    f.write("16: Mısır\n")
    f.write("* Teşekkür ederiz!\n")

# Üst sınıf oluştur "Pizza"
class Pizza:
    def __init__(self):
        self._description = "Pizza"
        self._cost = 0.0

    def get_description(self):
        return self._description

    def get_cost(self):
        return self._cost

# Alt sınıf oluştur "KlasikPizza"
class KlasikPizza(Pizza):
    def __init__(self):
        super().__init__()
        self._description = "Klasik Pizza"
        self._cost = 20.0

# Alt sınıf oluştur "MargaritaPizza"
class MargaritaPizza(Pizza):
    def __init__(self):
        super().__init__()
        self._description = "Margarita Pizza"
        self._cost = 25.0

# Alt sınıf oluştur "TürkPizza"
class TurkPizza(Pizza):
    def __init__(self):
        super().__init__()
        self._description = "Türk Pizza"
        self._cost = 30.0

# Alt sınıf oluştur "SadePizza"
class SadePizza(Pizza):
    def __init__(self):
        super().__init__()
        self._description = "Sade Pizza"
        self._cost = 15.0

# Üst sınıf oluştur "Decorator"
class Decorator(Pizza):
    def __init__(self, pizza):
        super().__init__()
        self._pizza = pizza

    def get_description(self):
        return self._pizza.get_description()

    def get_cost(self):
        return self._pizza.get_cost()

# Alt sınıf oluştur "ZeytinSosu"
class ZeytinSosu(Decorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self._description = self._pizza.get_description() + " + Zeytin Sosu"
        self._cost = self._pizza.get_cost() + 2.0

# Alt sınıf oluştur "MantarSosu"
class MantarSosu(Decorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self._description = self._pizza.get_description() + " + Mantar Sosu"
        self._cost = self._pizza.get_cost() + 3.0

# Alt sınıf oluştur "KeçiPeyniriSosu"
class KeçiPeyniriSosu(Decorator):
    def __init__(self, pizza):
        super().__init__(pizza)
        self._description = self

# Load data
        data_url = 'https://github.com/mwaskom/seaborn-data/raw/master/iris.csv'
        data = pd.read_csv(data_url)

# Create chart
        chart = alt.Chart(data).mark_point().encode(
            x='petal_length',
            y='petal_width',
            color='species'
        ).interactive()

# Display chart using Streamlit
        st.write(chart)

# Create a title for your app
        st.title("My First Streamlit App")

# Add some text to your app
        st.write("Welcome to my app!")

# Add a button to your app
        if st.button("Click me!"):
            st.write("You clicked the button!")

# Add a slider to your app
        number = st.slider("Select a number", 0, 10)
        st.write(f"You selected the number {number}")

